### ISSUE TITLE
how to set value to if the path path does not exist

### ISSUE THREAD

**Issue by maxzod** [dart-lang/yaml_edit#12]
iam working on `CLI` features that
see the content of the `assets` directory and add pathes to `pubspec.yaml` based on that 
it works with update if there is already a list in pubspec assets 
```dart
    final doc = YamlEditor(pubspecContent);
    doc.update(['flutter','assets'], assets);
```
**BUT** if there is no assets key n the pubspec under flutter
```yaml

flutter:
  uses-material-design: true
```
it throws exception 

i think this is the expected behavior to throw when updating a null but how could i `set` value to a key that does not exist+

**Comment by jonasfj** [comment]
@maxzod, you should be able to insert a new key in a `YamlMap` using `YamlEditor.

Can you make provide a complete minimal example of this issue?

**Comment by jonasfj** [comment]
I have no issues doing:
```dart
import 'package:yaml_edit/yaml_edit.dart';

void main() {
  final yamlEditor = YamlEditor('''
flutter:
  uses-material-design: true
''');
  yamlEditor.update([
    'flutter',
    'assets'
  ], {
    'foo': 'foo.jpg',
    'bar': 'bar.png',
  });
  print(yamlEditor.toString());
}
```
that prints:
```yaml
flutter:
  assets:
    foo: foo.jpg
    bar: bar.png
  uses-material-design: true
```
