### ISSUE TITLE
the YamlEditor.update method can leave trailing spaces at eol

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/yaml_edit#29]
Unit test repro included; for some cases, the `YamlEditor.update` method can leave trailing spaces at eol. So below, where we'd expect `updates:`, we instead get `updates:□`.

```
  test('no trailing whitespace', () {
    final editor = YamlEditor('''
updates: null
''');
    editor.update(['updates'], ['foo']);

    expect(editor.toString(), '''
updates:
  - foo
''');
  });
```

**Comment by jonasfj** [comment]
Makes sense that this can happen when rewriting from `null` to list in block mode.

Probably, it can also happen if rewriting from `"foo"` to list or object in block mode.

**Comment by Ishad-M-I-M** [comment]
Hi @jonasfj .
Can I get this assigned to me

**Comment by jonasfj** [comment]
sure!

**Comment by Ishad-M-I-M** [comment]
Hi @jonasfj .
Fix to this issue breaks some of the existing testcases as they are written such that to leave a whitespace at eol on update.

4 of existing testcases in `update_test.dart` fails. Below is an example.
```dart
      test('nested (8)', () {
        final doc = YamlEditor('''
a:
b: false
''');
        doc.update(['a'], {'retry': '3.0.1'});

        expect(doc.toString(), equals('''
a: 
  retry: 3.0.1
b: false
'''));
      });
```
This fails with following message.
```
Expected: 'a: \n'
            '  retry: 3.0.1\n'
            'b: false\n'
            ''
  Actual: 'a:\n'
            '  retry: 3.0.1\n'
            'b: false\n'
            ''
   Which: is different.
          Expected: a: \n  retry ...
            Actual: a:\n  retry: ...
                      ^
           Differ at offset 2
```
Should I need to reformat these expected result string by removing whitespace at eol?

**Comment by jonasfj** [comment]
> Should I need to reformat these expected result string by removing whitespace at eol?

Yes -- I think it's entirely possible that test cases also have bugs :D
