### ISSUE TITLE
Default chomping indicator in `ScalarStyle.LITERAL`

### ISSUE THREAD

**Issue by kekavc24** [dart-lang/yaml_edit#86]
It seems `ScalarStyle.LITERAL` applies the `stripping` chomping indicator `-` by default. 

https://github.com/dart-lang/yaml_edit/blob/561309eeb5fda2564dd08bbe790c18113dec8aa7/lib/src/strings.dart#L117-L129

`ScalarStyle.FOLDED` at least checks if there is any line break.

https://github.com/dart-lang/yaml_edit/blob/561309eeb5fda2564dd08bbe790c18113dec8aa7/lib/src/strings.dart#L92-L115

## Expected Behaviour
As indicated in the [spec], we should check for both `line breaks` & `trailing spaces` in order to apply the correct chomping indicator for block styles:

- `-` for stripping any trailing line breaks/spaces (strip)
- `+` for preserving trailing line breaks/spaces (keep)
- Omitting them preserves the line breaks but removes the trailing space (clip)

Ideally, we should end up using the `keep` chomping indicator `+` only since we may have no use for the `strip` chomping indicator `-`.

Fixing this may have desirable ripple effects for #41 & #44.

[spec]: https://yaml.org/spec/1.2.2/#812-literal-style:~:text=the%20indicated%20level.-,8.1.1.2.%20Block%20Chomping%20Indicator,content.%20These%20additional%20lines%20are%20not%20subject%20to%20folding.,-The%20chomping%20method

**Comment by kekavc24** [comment]
@jonasfj should the string from the user be preserved "as is" when inserting it in the yaml or should we mutate it to match the behaviour of `yaml`?

By "as-is", I mean should we respect how the user wants it look like when it is parsed by `package:yaml` ?

**Comment by jonasfj** [comment]
> should the string from the user be preserved "as is" when inserting it in the yaml or should we mutate it to match the behaviour of yaml?

I'm not sure exactly what this means.

If I do:
```dart
final myString = 'my string....';

yamlEditor.update(['key'], myString);
final result = json.decode(json.encode(yamlEditor.parseAt([])));
assert(result['key'] == myString);
```
Meaning, when I insert a string then, yes, when I parse the YAML document produced I expect I'll get the same string out.

That's what makes literal and folded strings somewhat tricky.
There are values that cannot be correctly encoded in folded and literal mode.

Example: try encoding `"  \nfoo"` in folded mode or literal mode. When we run into a scenario where we've been given a `YamlScalar`, where `YamlScalar.style` is folded or literal, and `YamlScalar.value` is a string that can't be encoded in said style, we have to fallback to most similar mode that can be used.

Sometimes I suppose that using a chomping indicator might help. Many times I suspect we'll simply have to fallback to quoted string with escape characters `"  \nfoo"`.

The most important thing is that the result is correct, when parsed back. Producing the style requested is more of a best-effort approach.

And yes, there clearly are hole in how all this logic works today.

------------------

I don't know if we can always make the chomping indicator be `+`, how would we encode a string like `"foo\nbar"` for that we need to use `>-\n  foo\n  bar\n` (if folded) or `|-\n  foo\n  bar\n` (if literal). Right?

**Comment by kekavc24** [comment]
> I don't know if we can always make the chomping indicator be `+`, how would we encode a string like `"foo\nbar"` for that we need to use `>-\n foo\n bar\n` (if folded) or `|-\n foo\n bar\n` (if literal). Right?

That would result in `foo  bar`. The `\n` will be converted to a [`space`](https://yaml.org/spec/1.2.2/#65-line-folding:~:text=Otherwise%20(the%20following%20line%20is%20not%20empty)%2C%20the%20line%20break%20is%20converted%20to%20a%20single%20space%20(x20))

To achieve: 
1. `foo\nbar`, we just add another `\n` and it becomes `>foo\n\nbar`. No need for chomping. Default behaviour for `YamlEditor` but messes with option 2.
2. `foo\n bar`, we leave untouched `>foo\n bar`. No need for chomping.

The real pain is: `whitespace\n \nbetween line breaks`. I think for that we have to fall back to a safe approach. I have tried all solutions and it's not coming out as expected with my fix. I am still at it.

I'll make a PR by the end of the day for your feedback and add this `whitespace\n \nbetween line breaks` as a test case in `string_test.dart`.

**Comment by jonasfj** [comment]
> 1. `foo\nbar`, we just add another `\n` and it becomes `>\n  foo\n\n   bar`. No need for chomping. Default behaviour for `YamlEditor` but messes with option 2.

Yeah, I got this example wrong :see_no_evil: 

Which probably is another example of how these strings are hard.

But you do need the `-` chomping indicator, if you have something like:
```yaml
key1: >-  # <-- omitting the chomping indicator will add \n at the end
  foo


  bar
key2: other-value
```

It's easy to see this if you use a tool like: https://onlineyamltools.com/convert-yaml-to-json

-------------------------
